@startuml
package "Aplikacja" {
  [MainWindow] --> [DatabaseManager] : korzysta z
  [RecordItemWidget] --> [DatabaseManager] : odczyt / zapis
}

package "Baza Danych" {
  [uniterm]
}

[DatabaseManager] --> [uniterm] : CRUD operacje

@enduml
